# The endpoint of the Azure AI Foundry project where your Agent will be created. It can be found in the project overview page. For example, https://my-resource.services.ai.azure.com/api/projects/my-project
project_endpoint: 

# The name of model deployment to be used for your Agent. 
model_name: 

# The endpoint for Azure AI Language service resource, Azure hub resource or Azure AI Foundry resource where your CLU and CQA projects are created. For example, https://my-resource.cognitiveservices.azure.com
language_resource_url: 

# The connection name of the above resource when added in the Azure AI Foundry portal to your project
language_resource_connection_name: 

# Go to the page of above connection in the Azure AI Foundry portal, then construct the connection ID by append "/connections/<language_resource_connection_name>" to the wsid parameter value in the page URL.
# For example, if the connection page URL contains "wsid=/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.CognitiveServices/accounts/<account_name>/projects/<project_name>", 
# Then the connection ID is /subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.CognitiveServices/accounts/<account_name>/projects/<project_name>/connections/<language_resource_connection_name>
connection_id: 

# Project and deployment names for Conversational Language Understanding (CLU) and Custom Question Answering (CQA) that your Agent will use. 
cqa_project_name: 
cqa_deployment_name: 
clu_project_name: 
clu_deployment_name: 